# fly.toml app configuration file generated for wastewise-frontend on 2025-06-14T17:03:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wastewise-frontend'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
guest_path = "/usr/share/nginx/html"
url_prefix = "/"
fallback = "/index.html"