app = "wastewise-database"  # Ganti jika Fly.io kasih nama lain

primary_region = "sin"  # Lokasi server, misal: Singapore

[build]
  dockerfile = "Dockerfile"

[env]
  COUCHDB_USER = "Wilson"
  COUCHDB_PASSWORD = "W1l$0n30"

[[services]]
  internal_port = 5984
  protocol = "tcp"

  [[services.ports]]
    port = 80  # agar bisa diakses via http://

  [[services.ports]]
    port = 443 # agar bisa diakses via https://

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
