# fly.toml app configuration file generated for wastewise-database on 2025-06-14T14:48:36+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wastewise-database'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5984
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="couchdb_data"
  destination="/opt/couchdb/data"